---
name: Build keycloak container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-keycloak-container-image.yml
      - keycloak/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-keycloak-container-image.yml
      - keycloak/**

jobs:

  build-keycloak-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 23.0.3  # Select the correct version / ask what this does
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Build container image
        run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: scs-keycloak
          REPOSITORY: scs-container-images/scs-keycloak
          VERSION: ${{ matrix.version }}

      - name: Push container image
        run: scripts/push.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          IMAGE: scs-keycloak
          REPOSITORY: scs-container-images/scs-keycloak
          VERSION: ${{ matrix.version }}
        if: |
          github.repository == 'SovereignCloudStack/container-images' &&
          github.ref == 'refs/heads/main'
